"""S1: 全量 20 表首版迁移

Revision ID: afeffa03da10
Revises: 
Create Date: 2026-09-02 15:50:58.412944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

import app.core.database  # BigInt 跨方言类型（MySQL BIGINT / SQLite INTEGER）

# revision identifiers, used by Alembic.
revision: str = 'afeffa03da10'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_action_log',
    sa.Column('id', app.core.database.BigInt(), autoincrement=True, nullable=False),
    sa.Column('admin_id', app.core.database.BigInt(), nullable=False),
    sa.Column('action', sa.SmallInteger(), nullable=False),
    sa.Column('target_type', sa.SmallInteger(), nullable=True),
    sa.Column('target_id', app.core.database.BigInt(), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='管理员操作日志：全部处置留痕'
    )
    op.create_table('answer',
    sa.Column('id', app.core.database.BigInt(), autoincrement=True, nullable=False),
    sa.Column('post_id', app.core.database.BigInt(), nullable=False),
    sa.Column('author_id', app.core.database.BigInt(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_accepted', sa.SmallInteger(), nullable=False),
    sa.Column('is_best', sa.SmallInteger(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='回答：已被采纳不可编辑/删除（40905/40906）'
    )
    op.create_index('idx_answer_accepted', 'answer', ['post_id', 'is_accepted'], unique=False)
    op.create_index('idx_answer_author', 'answer', ['author_id'], unique=False)
    op.create_index('idx_answer_post', 'answer', ['post_id'], unique=False)
    op.create_table('app_config',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', mysql.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('key'),
    comment='运行时配置：覆盖 env 默认值（积分分值/阈值等）'
    )
    op.create_table('comment',
    sa.Column('id', app.core.database.BigInt(), autoincrement=True, nullable=False),
    sa.Column('target_type', sa.SmallInteger(), nullable=False),
    sa.Column('target_id', app.core.database.BigInt(), nullable=False),
    sa.Column('author_id', app.core.database.BigInt(), nullable=False),
    sa.Column('parent_id', app.core.database.BigInt(), nullable=True),
    sa.Column('reply_to_user_id', app.core.database.BigInt(), nullable=True),
    sa.Column('content', sa.String(length=500), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='双层评论：parent 非 NULL 必须指向根评论（二层封顶）'
    )
    op.create_index('idx_comment_target', 'comment', ['target_type', 'target_id'], unique=False)
    op.create_table('credit_log',
    sa.Column('id', app.core.database.BigInt(), autoincrement=True, nullable=False),
    sa.Column('user_id', app.core.database.BigInt(), nullable=False),
    sa.Column('change', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('source', sa.SmallInteger(), nullable=False),
    sa.Column('ref_type', sa.SmallInteger(), nullable=True),
    sa.Column('ref_id', app.core.database.BigInt(), nullable=True),
    sa.Column('note', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='积分流水：全量记录，balance_after 保证连续性'
    )
    op.create_index('idx_user_date', 'credit_log', ['user_id', 'created_at'], unique=False)
    op.create_table('favorite',
    sa.Column('user_id', app.core.database.BigInt(), nullable=False),
    sa.Column('target_type', sa.SmallInteger(), nullable=False),
    sa.Column('target_id', app.core.database.BigInt(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'target_type', 'target_id'),
    comment='收藏：评论不可收藏由服务层校验（40910）'
    )
    op.create_index('idx_favorite_target', 'favorite', ['target_type', 'target_id'], unique=False)
    op.create_table('gratitude_stat',
    sa.Column('user_id', app.core.database.BigInt(), nullable=False),
    sa.Column('period_type', sa.SmallInteger(), nullable=False),
    sa.Column('period_key', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'period_type', 'period_key'),
    comment='感谢值统计：采纳时实时 +30'
    )
    op.create_table('knowledge_item',
    sa.Column('post_id', app.core.database.BigInt(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('post_id'),
    comment='知识库收录：仅存 post_id 引用，内容随帖联查不冗余'
    )
    op.create_table('like_record',
    sa.Column('user_id', app.core.database.BigInt(), nullable=False),
    sa.Column('target_type', sa.SmallInteger(), nullable=False),
    sa.Column('target_id', app.core.database.BigInt(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'target_type', 'target_id'),
    comment='点赞：联合主键天然幂等'
    )
    op.create_index('idx_like_target', 'like_record', ['target_type', 'target_id'], unique=False)
    op.create_table('notification',
    sa.Column('id', app.core.database.BigInt(), autoincrement=True, nullable=False),
    sa.Column('user_id', app.core.database.BigInt(), nullable=False),
    sa.Column('type', sa.SmallInteger(), nullable=False),
    sa.Column('actor_id', app.core.database.BigInt(), nullable=False),
    sa.Column('target_type', sa.SmallInteger(), nullable=False),
    sa.Column('target_id', app.core.database.BigInt(), nullable=False),
    sa.Column('is_read', sa.SmallInteger(), nullable=False),
    sa.Column('invalid', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='站内通知：五类互动'
    )
    op.create_index('idx_user_read', 'notification', ['user_id', 'is_read'], unique=False)
    op.create_table('post',
    sa.Column('id', app.core.database.BigInt(), autoincrement=True, nullable=False),
    sa.Column('author_id', app.core.database.BigInt(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('images', mysql.JSON(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('reward', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('answer_count', sa.Integer(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('last_answer_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('ai_summary', sa.String(length=200), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='帖子：images 为 JSON 数组；软删见 deleted_at'
    )
    op.create_index('idx_post_author', 'post', ['author_id'], unique=False)
    op.create_index('idx_post_last_answer', 'post', ['last_answer_at'], unique=False)
    op.create_index('idx_post_status', 'post', ['status'], unique=False)
    op.create_table('rank_snapshot',
    sa.Column('id', app.core.database.BigInt(), autoincrement=True, nullable=False),
    sa.Column('period_type', sa.SmallInteger(), nullable=False),
    sa.Column('period_key', sa.String(length=10), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('user_id', app.core.database.BigInt(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_type', 'period_key', 'rank', name='uk_period_rank'),
    comment='榜单快照：结算任务写入，榜单公布以此为准（防历史数据变动）'
    )
    op.create_table('report',
    sa.Column('id', app.core.database.BigInt(), autoincrement=True, nullable=False),
    sa.Column('reporter_id', app.core.database.BigInt(), nullable=False),
    sa.Column('target_type', sa.SmallInteger(), nullable=False),
    sa.Column('target_id', app.core.database.BigInt(), nullable=False),
    sa.Column('reason', sa.SmallInteger(), nullable=False),
    sa.Column('detail', sa.String(length=200), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('handled_by', app.core.database.BigInt(), nullable=True),
    sa.Column('result', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reporter_id', 'target_type', 'target_id', name='uk_dedup'),
    comment='举报：唯一键去重（40903）'
    )
    op.create_index('idx_report_status', 'report', ['status'], unique=False)
    op.create_table('tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tracking_event',
    sa.Column('id', app.core.database.BigInt(), autoincrement=True, nullable=False),
    sa.Column('user_id', app.core.database.BigInt(), nullable=True),
    sa.Column('event_name', sa.String(length=50), nullable=False),
    sa.Column('props', mysql.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='埋点事件：批量异步落库，失败不影响业务'
    )
    op.create_index('idx_event_time', 'tracking_event', ['event_name', 'created_at'], unique=False)
    op.create_table('user',
    sa.Column('id', app.core.database.BigInt(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('nickname', sa.String(length=20), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('school', sa.String(length=50), nullable=False),
    sa.Column('major', sa.String(length=50), nullable=False),
    sa.Column('theme_config', mysql.JSON(), nullable=True),
    sa.Column('role', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('banned_until', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone'),
    comment='用户表：手机号为主账号（MVP 无认证）'
    )
    op.create_index('idx_major', 'user', ['major'], unique=False)
    op.create_index('idx_school', 'user', ['school'], unique=False)
    op.create_table('credit_account',
    sa.Column('user_id', app.core.database.BigInt(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.CheckConstraint('balance >= 0', name='ck_balance_nonnegative'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    comment='积分账户：balance 恒非负，服务层行锁防透支'
    )
    op.create_table('post_tag',
    sa.Column('post_id', app.core.database.BigInt(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_tag')
    op.drop_table('credit_account')
    op.drop_index('idx_school', table_name='user')
    op.drop_index('idx_major', table_name='user')
    op.drop_table('user')
    op.drop_index('idx_event_time', table_name='tracking_event')
    op.drop_table('tracking_event')
    op.drop_table('tag')
    op.drop_index('idx_report_status', table_name='report')
    op.drop_table('report')
    op.drop_table('rank_snapshot')
    op.drop_index('idx_post_status', table_name='post')
    op.drop_index('idx_post_last_answer', table_name='post')
    op.drop_index('idx_post_author', table_name='post')
    op.drop_table('post')
    op.drop_index('idx_user_read', table_name='notification')
    op.drop_table('notification')
    op.drop_index('idx_like_target', table_name='like_record')
    op.drop_table('like_record')
    op.drop_table('knowledge_item')
    op.drop_table('gratitude_stat')
    op.drop_index('idx_favorite_target', table_name='favorite')
    op.drop_table('favorite')
    op.drop_index('idx_user_date', table_name='credit_log')
    op.drop_table('credit_log')
    op.drop_index('idx_comment_target', table_name='comment')
    op.drop_table('comment')
    op.drop_table('app_config')
    op.drop_index('idx_answer_post', table_name='answer')
    op.drop_index('idx_answer_author', table_name='answer')
    op.drop_index('idx_answer_accepted', table_name='answer')
    op.drop_table('answer')
    op.drop_table('admin_action_log')
    # ### end Alembic commands ###
